// <auto-generated />
namespace FW.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddNewTableBiddingPackageOther_ModifySomeFieldOfBiddingNews : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddNewTableBiddingPackageOther_ModifySomeFieldOfBiddingNews));
        
        string IMigrationMetadata.Id
        {
            get { return "201806241140019_AddNewTableBiddingPackageOther_ModifySomeFieldOfBiddingNews"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
