// <auto-generated />
namespace FW.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RemoveWorkContentColumnOfBiddingNews_AddColumnBiddingPackageTypeForBiddingPackage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RemoveWorkContentColumnOfBiddingNews_AddColumnBiddingPackageTypeForBiddingPackage));
        
        string IMigrationMetadata.Id
        {
            get { return "201811141659269_RemoveWorkContentColumnOfBiddingNews_AddColumnBiddingPackageTypeForBiddingPackage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
