// <auto-generated />
namespace FW.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_BiddingNews_Budget_Col : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_BiddingNews_Budget_Col));
        
        string IMigrationMetadata.Id
        {
            get { return "201901120822002_Add_BiddingNews_Budget_Col"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
