// <auto-generated />
namespace FW.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UpdateColumn_Company_TotalBiddedNews_ProjectImplemented : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdateColumn_Company_TotalBiddedNews_ProjectImplemented));
        
        string IMigrationMetadata.Id
        {
            get { return "201902170951574_UpdateColumn_Company_TotalBiddedNews_ProjectImplemented"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
