//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FW.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FW.Resources.CommonResource", typeof(CommonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận đăng ký tài khoản thất bại.
        /// </summary>
        public static string ERR_CONFIRM_EMAIL {
            get {
                return ResourceManager.GetString("ERR_CONFIRM_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập thất bại.
        /// </summary>
        public static string ERR_LOGIN_FAIL {
            get {
                return ResourceManager.GetString("ERR_LOGIN_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình hình tài chính trong {0} năm gần nhất không bị lỗ, có xác nhận hợp lệ của cơ quan tài chính cấp trên hoặc kiểm toán độc lập..
        /// </summary>
        public static string FinanceSituationAbilityFinance {
            get {
                return ResourceManager.GetString("FinanceSituationAbilityFinance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không bị kết luận đang lâm vào tình trạng phá sản hoặc nợ không có khả năng chi trả theo quy định của pháp luật.
        /// </summary>
        public static string IsBankruptTCHL {
            get {
                return ResourceManager.GetString("IsBankruptTCHL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giấy phép xây dựng hoặc văn bản phê duyệt dự án.
        /// </summary>
        public static string IsBuildingPermitAbilityExp {
            get {
                return ResourceManager.GetString("IsBuildingPermitAbilityExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp đồng mua bán hoặc hợp đồng thuê mượn hoặc hóa đơn mua thiết bị.
        /// </summary>
        public static string IsContractAbilityEquipment {
            get {
                return ResourceManager.GetString("IsContractAbilityEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp đồng.
        /// </summary>
        public static string IsContractAbilityExp {
            get {
                return ResourceManager.GetString("IsContractAbilityExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quyết định bổ nhiệm nhân sự (đối với những vị trí yêu cầu về số lượng công trình tương tự đã tham gia thực hiện).
        /// </summary>
        public static string IsDecisionAbilityHR {
            get {
                return ResourceManager.GetString("IsDecisionAbilityHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tờ khai tự quyết toán thuế (thuế GTGT và thuế thu nhập doanh nghiệp), có xác nhận của cơ quan thuế về thời điểm đã nộp tờ khai trong 02 năm tài chính nêu trên.
        /// </summary>
        public static string IsDeclarationAbilityFinance {
            get {
                return ResourceManager.GetString("IsDeclarationAbilityFinance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không đang trong quá trình giải thể.
        /// </summary>
        public static string IsDissolutionProcessTCHL {
            get {
                return ResourceManager.GetString("IsDissolutionProcessTCHL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Văn bản xác nhận của cơ quan quản lý thuế (xác nhận nộp cả năm) về việc thực hiện nghĩa vụ nộp thuế trong 02 năm tài chính nêu trên.
        /// </summary>
        public static string IsDocumentAbilityFinance {
            get {
                return ResourceManager.GetString("IsDocumentAbilityFinance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Văn bằng yêu cầu.
        /// </summary>
        public static string IsDocumentRequestAbilityHR {
            get {
                return ResourceManager.GetString("IsDocumentRequestAbilityHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng vẽ và thuyết minh biện pháp thi công.
        /// </summary>
        public static string IsDrawingConstructionMKT {
            get {
                return ResourceManager.GetString("IsDrawingConstructionMKT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuyết minh biện pháp đảm bảo vệ sinh môi trường.
        /// </summary>
        public static string IsEnvironmentalSanitationMKT {
            get {
                return ResourceManager.GetString("IsEnvironmentalSanitationMKT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hạch toán tài chính độc lập.
        /// </summary>
        public static string IsFinancialTCHL {
            get {
                return ResourceManager.GetString("IsFinancialTCHL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuyết minh phòng chống cháy nổ trên cổng trường.
        /// </summary>
        public static string IsFireProtectionMKT {
            get {
                return ResourceManager.GetString("IsFireProtectionMKT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp đồng lao động.
        /// </summary>
        public static string IsLaborContractAbilityHR {
            get {
                return ResourceManager.GetString("IsLaborContractAbilityHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản thanh lý hợp đồng hoặc biên bản nghiệm thu bàn giao công trình.
        /// </summary>
        public static string IsLiquidationAbilityExp {
            get {
                return ResourceManager.GetString("IsLiquidationAbilityExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng đề xuất vật tư sử dụng.
        /// </summary>
        public static string IsMaterialsUseMKT {
            get {
                return ResourceManager.GetString("IsMaterialsUseMKT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hồ sơ kiểm định của các máy móc (đối với các máy móc phải có yêu cầu kiểm định).
        /// </summary>
        public static string IsProfileAbilityEquipment {
            get {
                return ResourceManager.GetString("IsProfileAbilityEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng vẽ tiến độ thực hiện.
        /// </summary>
        public static string IsProgressScheduleMKT {
            get {
                return ResourceManager.GetString("IsProgressScheduleMKT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biên bản kiểm tra quyết toán của nhà thầu trong 02 năm tài chính nêu trên.
        /// </summary>
        public static string IsProtocolAbilityFinance {
            get {
                return ResourceManager.GetString("IsProtocolAbilityFinance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng báo giá.
        /// </summary>
        public static string IsQuotationMKT {
            get {
                return ResourceManager.GetString("IsQuotationMKT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có đăng ký thành lập, hoạt động do cơ quan có thẩm quyền của nước mà nhà thầu, nhà đầu tư đang hoạt động cấp.
        /// </summary>
        public static string IsRegisEstablishmentTCHL {
            get {
                return ResourceManager.GetString("IsRegisEstablishmentTCHL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo kiểm toán.
        /// </summary>
        public static string IsReportAbilityFinance {
            get {
                return ResourceManager.GetString("IsReportAbilityFinance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuyết minh phương pháp đảm bảo an toàn lao động.
        /// </summary>
        public static string IsWorkSafetyMKT {
            get {
                return ResourceManager.GetString("IsWorkSafetyMKT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application started..
        /// </summary>
        public static string LoggerAppStart {
            get {
                return ResourceManager.GetString("LoggerAppStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---------Begin method {0}..
        /// </summary>
        public static string LoggerBeginMethod {
            get {
                return ResourceManager.GetString("LoggerBeginMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---------End method {0}..
        /// </summary>
        public static string LoggerEndMethod {
            get {
                return ResourceManager.GetString("LoggerEndMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{Exception}} !!! \n.
        /// </summary>
        public static string LoggerException {
            get {
                return ResourceManager.GetString("LoggerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item đã tồn tại. Vui lòng kiểm tra lại hệ thống.
        /// </summary>
        public static string MSG_ERROR_EXIST_RECORD {
            get {
                return ResourceManager.GetString("MSG_ERROR_EXIST_RECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tồn tại item trong hệ thống. Vui lòng kiểm tra lại..
        /// </summary>
        public static string MSG_ERROR_NOT_EXIST_RECORD {
            get {
                return ResourceManager.GetString("MSG_ERROR_NOT_EXIST_RECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item đã bị xóa..
        /// </summary>
        public static string MSG_ERROR_RECORD_IS_DELETED {
            get {
                return ResourceManager.GetString("MSG_ERROR_RECORD_IS_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu hiện tại không phải là dữ liệu mới nhất. Vui lòng kiểm tra lại dữ liệu hệ thống..
        /// </summary>
        public static string MSG_ERROR_RECORD_OUT_OF_DATE {
            get {
                return ResourceManager.GetString("MSG_ERROR_RECORD_OUT_OF_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xảy ra lỗi hệ thống. Vui lòng liên hệ quản trị hệ thống của bạn..
        /// </summary>
        public static string MSG_ERROR_SYSTEM {
            get {
                return ResourceManager.GetString("MSG_ERROR_SYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthorityCheck.
        /// </summary>
        public static string SRC_LOGIN_ACT_AuthorityCheck {
            get {
                return ResourceManager.GetString("SRC_LOGIN_ACT_AuthorityCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string SRC_LOGIN_ACT_Logout {
            get {
                return ResourceManager.GetString("SRC_LOGIN_ACT_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tbl_BiddingNews.
        /// </summary>
        public static string TABLE_BIDDING_NEWS {
            get {
                return ResourceManager.GetString("TABLE_BIDDING_NEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tbl_BiddingDetail.
        /// </summary>
        public static string TABLE_BIDDINGDETAIL {
            get {
                return ResourceManager.GetString("TABLE_BIDDINGDETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tbl_CompanyAbilityEquipment.
        /// </summary>
        public static string TABLE_COMPANYABILITYEQUIPMENT {
            get {
                return ResourceManager.GetString("TABLE_COMPANYABILITYEQUIPMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tbl_CompanyAbilityExp.
        /// </summary>
        public static string TABLE_COMPANYABILITYEXP {
            get {
                return ResourceManager.GetString("TABLE_COMPANYABILITYEXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tbl_CompanyAbilityFinance.
        /// </summary>
        public static string TABLE_COMPANYABILITYFINANCE {
            get {
                return ResourceManager.GetString("TABLE_COMPANYABILITYFINANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tbl_CompanyAbilityHr.
        /// </summary>
        public static string TABLE_COMPANYABILITYHR {
            get {
                return ResourceManager.GetString("TABLE_COMPANYABILITYHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tbl_CompanyProfile.
        /// </summary>
        public static string TABLE_COMPANYPROFILE {
            get {
                return ResourceManager.GetString("TABLE_COMPANYPROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tbl_construction.
        /// </summary>
        public static string TABLE_CONSTRUCTION {
            get {
                return ResourceManager.GetString("TABLE_CONSTRUCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tbl_LOGIN_HISTORY.
        /// </summary>
        public static string TABLE_LOGIN_HISTORY {
            get {
                return ResourceManager.GetString("TABLE_LOGIN_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tbl_users.
        /// </summary>
        public static string TABLE_USERS {
            get {
                return ResourceManager.GetString("TABLE_USERS", resourceCulture);
            }
        }
    }
}
