//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FW.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LoginMessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoginMessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FW.Resources.LoginMessageResource", typeof(LoginMessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account đang không hoạt động. Vui lòng liên hệ admin..
        /// </summary>
        public static string AccountIsLock {
            get {
                return ResourceManager.GetString("AccountIsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username đăng nhập này đã bị khóa vì bạn đã đăng nhập sai 5 lần. Vui lòng click &quot;Quên mật khẩu&quot; hoặc liên hệ Admin..
        /// </summary>
        public static string AccountLoginFailed5Times {
            get {
                return ResourceManager.GetString("AccountLoginFailed5Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account không tồn tại trong hệ thống. Vui lòng thử lại..
        /// </summary>
        public static string AccountNotExist {
            get {
                return ResourceManager.GetString("AccountNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username hoặc mật khẩu không đúng. Vui lòng thử lại..
        /// </summary>
        public static string ErrorValid {
            get {
                return ResourceManager.GetString("ErrorValid", resourceCulture);
            }
        }
    }
}
