// <auto-generated />
namespace FW.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddColumnUserIdTo_BiddingNews_And_Company : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddColumnUserIdTo_BiddingNews_And_Company));
        
        string IMigrationMetadata.Id
        {
            get { return "201811100645380_AddColumnUserIdTo_BiddingNews_And_Company"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
