// <auto-generated />
namespace FW.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AdditionalFieldsToBiddingDetail_20180625 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdditionalFieldsToBiddingDetail_20180625));
        
        string IMigrationMetadata.Id
        {
            get { return "201806251153395_AdditionalFieldsToBiddingDetail_20180625"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
