// <auto-generated />
namespace FW.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Modified_MaxLength_Company_CompanyName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Modified_MaxLength_Company_CompanyName));
        
        string IMigrationMetadata.Id
        {
            get { return "201904081457206_Modified_MaxLength_Company_CompanyName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
