// <auto-generated />
namespace FW.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Modify__Columnname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Modify__Columnname));
        
        string IMigrationMetadata.Id
        {
            get { return "201901291611367_Modify__Columnname"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
