// <auto-generated />
namespace FW.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class V2_Remove_unique_index_of_Username_table_post : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V2_Remove_unique_index_of_Username_table_post));
        
        string IMigrationMetadata.Id
        {
            get { return "202407311553503_V2_Remove_unique_index_of_Username_table_post"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
