// <auto-generated />
namespace FW.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class V4_Rename_column_thumbnail_Post : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V4_Rename_column_thumbnail_Post));
        
        string IMigrationMetadata.Id
        {
            get { return "202408111021152_V4_Rename_column_thumbnail_Post"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
