// <auto-generated />
namespace FW.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class V5_Update_content_column_type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V5_Update_content_column_type));
        
        string IMigrationMetadata.Id
        {
            get { return "202408230535336_V5_Update_content_column_type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
